In [17]:
import pandas as pd
import numpy as np

books = pd.read_csv('books.csv')
ratings = pd.read_csv('ratings.csv')
users = pd.read_csv('users.csv')

C:\Users\anush\AppData\Local\Temp\ipykernel_22620\569542028.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')

In [18]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [19]:
ratings_name = ratings.merge(books, on = "ISBN")

In [20]:
ratings_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [23]:
new_ratings = ratings_name.groupby("Book-Title")["Book-Rating"].mean().reset_index()
new_ratings.rename(columns = {"Book-Rating" : "Avg Ratings"}, inplace = True)

In [24]:
new_ratings

                                               Book-Title  Avg Ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [28]:
new_ratings

                                               Book-Title  Avg Ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [29]:
new_ratings.merge(new_ratings, ratings_name, on ="Book-Title")

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [35]:
popular_df = new_ratings.merge(ratings_name, on="Book-Title")

In [36]:
popular_df.reset_index()

,index,Book-Title,Avg Ratings,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0,A Light in the Storm: The Civil War Diary of ...,2.250000,18995,0590567330,0,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
1,1,A Light in the Storm: The Civil War Diary of ...,2.250000,35859,0590567330,0,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
2,2,A Light in the Storm: The Civil War Diary of ...,2.250000,55927,0590567330,0,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
3,3,A Light in the Storm: The Civil War Diary of ...,2.250000,96448,0590567330,9,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
4,4,Always Have Popsicles,0.000000,172742,0964147726,0,Rebecca Harvin,1994,Rebecca L. Harvin,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...
...,...,...,...,...,...,...,...,...,...,...,...,...
1031131,1031131,Ã?Â?stlich der Berge.,2.666667,90839,3442725739,8,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
1031132,1031132,Ã?Â?stlich der Berge.,2.666667,243548,3442725739,0,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
1031133,1031133,Ã?Â?stlich der Berge.,2.666667,261105,3442725739,0,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
1031134,1031134,Ã?Â?thique en toc,4.000000,25436,2842192508,8,Didier Daeninckx,1998,Baleine,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...
1031135,1031135,Ã?Â?thique en toc,4.000000,53628,2842192508,0,Didier Daeninckx,1998,Baleine,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...

In [37]:
popular_df = new_ratings.merge(new_ratings, ratings_name, on = "Book-Title")

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [38]:
import numpy as np
import pandas as pd

books = pd.read_csv("Books.csv")
users = pd.read_csv("Users.csv")
ratings = pd.read_csv("Ratings.csv")

ratings_with_name = ratings.merge(books, on='ISBN')


num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating': 'num_ratings'}, inplace=True)


avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Book-Rating': 'avg_rating'}, inplace=True)


result_df = pd.merge(num_rating_df, avg_rating_df, on='Book-Title')


result_df

C:\Users\anush\AppData\Local\Temp\ipykernel_22620\1884039497.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [39]:
popular_df = result_df.merge(avg_rating_df, on = "Book-Title")

In [40]:
popular_df

,Book-Title,num_ratings,avg_rating_x,avg_rating_y
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000,2.250000
1,Always Have Popsicles,1,0.000000,0.000000
2,Apple Magic (The Collector's series),1,0.000000,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000,0.000000
...,...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667,2.666667
241070,Ã?Â?thique en toc,2,4.000000,4.000000

In [54]:
top_rating = popular_df[popular_df['num_ratings'] >= 250]

In [56]:
top_rating.sort_values("avg_rating_x", ascending=False).head(50)

,Book-Title,num_ratings,avg_rating_x,avg_rating_y
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769,4.880769
219741,To Kill a Mockingbird,510,4.700000,4.700000
183573,The Da Vinci Code,898,4.642539,4.642539
187880,The Five People You Meet in Heaven,430,4.551163,4.551163
180556,The Catcher in the Rye,449,4.545657,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726,4.468726
764,1984,284,4.454225,4.454225
144165,Prodigal Summer: A Novel,253,4.450593,4.450593
128670,Neverwhere,265,4.449057,4.449057
206502,The Secret Life of Bees,774,4.447028,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552,4.289552
93381,Into the Wild,252,4.273810,4.273810
63867,Fahrenheit 451,409,4.264059,4.264059
74750,Girl with a Pearl Earring,526,4.218631,4.218631
136145,Outlander,283,4.173145,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983,4.105983
156102,Seabiscuit: An American Legend,275,4.098182,4.098182
107962,Life of Pi,664,4.088855,4.088855
176845,The Bean Trees,389,4.087404,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792,4.086792
8434,ANGELA'S ASHES,279,4.075269,4.075269
76343,Good in Bed,490,4.055102,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,4.037383
12700,American Gods,302,4.006623,4.006623
161645,Skipping Christmas,322,4.006211,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000,4.000000
181679,The Color Purple,314,3.964968,3.964968
160336,Silence of the Lambs,256,3.960938,3.960938
8752,About a Boy,262,3.900763,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569,3.820569
111073,Lord of the Flies,259,3.818533,3.818533
5664,A Prayer for Owen Meany,413,3.796610,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472,3.772472

In [67]:
given_rating = top_rating.merge(books, on = "Book-Title").drop_duplicates("Book-Title").sort_values("num_ratings", ascending=False).sort_values("avg_rating_x", ascending=False)

In [71]:
given_rating.rename(columns={"avg_rating_x" : "avg_rating"}).drop(columns={"avg_rating_y"})

,Book-Title,num_ratings,avg_rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
226,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
220,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
229,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
222,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
217,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...
...,...,...,...,...,...,...,...,...,...,...
696,Vinegar Hill (Oprah's Book Club (Paperback)),265,2.245283,0380730138,A. Manette Ansay,1998,Perennial,http://images.amazon.com/images/P/0380730138.0...,http://images.amazon.com/images/P/0380730138.0...,http://images.amazon.com/images/P/0380730138.0...
722,Whispers,286,2.199301,0440216745,BELVA PLAIN,1994,Dell,http://images.amazon.com/images/P/0440216745.0...,http://images.amazon.com/images/P/0440216745.0...,http://images.amazon.com/images/P/0440216745.0...
345,Presumed Innocent,294,2.139456,0446359866,Scott Turow,1989,Warner Books,http://images.amazon.com/images/P/0446359866.0...,http://images.amazon.com/images/P/0446359866.0...,http://images.amazon.com/images/P/0446359866.0...
258,Isle of Dogs,288,2.000000,0425182908,Patricia Cornwell,2002,Berkley Publishing Group,http://images.amazon.com/images/P/0425182908.0...,http://images.amazon.com/images/P/0425182908.0...,http://images.amazon.com/images/P/0425182908.0...
737,Wild Animus,2502,1.019584,0971880107,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...