In [1]:
import pandas as pd
import numpy as np

books = pd.read_csv('books.csv')
ratings = pd.read_csv('ratings.csv')
users = pd.read_csv('users.csv')

C:\Users\anush\AppData\Local\Temp\ipykernel_26396\569542028.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')

In [2]:
ratings_with_name = ratings.merge(books, on = "ISBN")

In [3]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating': 'num_ratings'}, inplace=True)

In [6]:
avg_rating = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()
avg_rating.rename(columns={'Book-Rating': 'avg_ratings'}, inplace=True)

pandas.core.frame.DataFrame

In [8]:
avg_rating['avg_ratings'] = avg_rating['avg_ratings'].round().astype(int)
avg_rating

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...            2
1                                   Always Have Popsicles            0
2                    Apple Magic (The Collector's series)            0
3        Ask Lily (Young Women of Faith: Lily Series, ...            8
4        Beyond IBM: Leadership Marketing and Finance ...            0
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            0
241067                     Ã?Â?rger mit Produkt X. Roman.            5
241068                                Ã?Â?sterlich leben.            7
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            4

[241071 rows x 2 columns]

In [10]:
popular_df = num_rating_df.merge(avg_rating, on = "Book-Title")
popular_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2
1,Always Have Popsicles,1,0
2,Apple Magic (The Collector's series),1,0
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8
4,Beyond IBM: Leadership Marketing and Finance ...,1,0
...,...,...,...
241066,Ã?Â?lpiraten.,2,0
241067,Ã?Â?rger mit Produkt X. Roman.,4,5
241068,Ã?Â?sterlich leben.,1,7
241069,Ã?Â?stlich der Berge.,3,3
241070,Ã?Â?thique en toc,2,4

In [11]:
basic_df = popular_df[popular_df["num_ratings"]>=250].sort_values('avg_ratings', ascending=False).reset_index()
basic_df

,index,Book-Title,num_ratings,avg_ratings
0,80441,Harry Potter and the Sorcerer's Stone (Book 1),278,6
1,80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,6
2,80426,Harry Potter and the Order of the Phoenix (Boo...,347,6
3,80422,Harry Potter and the Goblet of Fire (Book 4),387,6
4,80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,5
...,...,...,...,...
181,203176,The Prince of Tides,291,2
182,233635,Whispers,286,2
183,150473,Rising Sun,278,2
184,143377,Presumed Innocent,294,2
185,234951,Wild Animus,2502,1

In [12]:
best_df = basic_df.merge(books, on = "Book-Title").drop_duplicates('Book-Title')[['Book-Title', 'Book-Author', 'Image-URL-S', 'num_ratings', 'avg_ratings']]

In [13]:
best_df.head(50)

,Book-Title,Book-Author,Image-URL-S,num_ratings,avg_ratings
0,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,6
4,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,6
7,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,6
11,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,6
13,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,5
15,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,5
23,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,5
29,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,5
38,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,5
40,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5
41,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5
44,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,5
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,5
62,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4
64,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,4
70,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4
76,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,291,4
77,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4
79,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4
84,Misery,Stephen King,http://images.amazon.com/images/P/0451153553.0...,291,4
92,Me Talk Pretty One Day,David Sedaris,http://images.amazon.com/images/P/0316776963.0...,457,4
96,Lucky : A Memoir,Alice Sebold,http://images.amazon.com/images/P/0316096199.0...,301,4
97,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4
101,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4
110,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4
112,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4
115,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,4
122,Interview with the Vampire,Anne Rice,http://images.amazon.com/images/P/0345337662.0...,508,4
124,Insomnia,Stephen King,http://images.amazon.com/images/P/0670855030.0...,260,4
129,The Nanny Diaries: A Novel,Emma McLaughlin,http://images.amazon.com/images/P/0312278586.0...,828,4
131,The Notebook,Nicholas Sparks,http://images.amazon.com/images/P/0446605239.0...,650,4
136,White Oleander : A Novel,Janet Fitch,http://images.amazon.com/images/P/0316182540.0...,387,4
139,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4
140,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,4
142,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4
144,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4
147,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,4
153,Wicked: The Life and Times of the Wicked Witch...,Gregory Maguire,http://images.amazon.com/images/P/0060987103.0...,326,4
154,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,4
156,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,4
160,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,4
161,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4
162,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4
168,Red Dragon,Thomas Harris,http://images.amazon.com/images/P/0440206154.0...,402,4
176,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,4
179,She's Come Undone (Oprah's Book Club),Wally Lamb,http://images.amazon.com/images/P/0671021001.0...,468,4
180,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,4
182,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4
184,1st to Die: A Novel,James Patterson,http://images.amazon.com/images/P/0446610038.0...,509,4
186,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4

In [14]:
#Collabrative filtering based now ->

x = ratings_with_name.groupby("User-ID").count()['Book-Rating']>250

padhe_likhe = x[x].index

In [15]:
filtered_rating = ratings_with_name[ratings_with_name["User-ID"].isin(padhe_likhe)]

In [16]:
y = filtered_rating.groupby("Book-Title").count()["Book-Rating"]>=50
famous_books = y[y].index

In [17]:
finals_rating = filtered_rating[filtered_rating["Book-Title"].isin(famous_books)]

In [18]:
finals_rating.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1025422,264317,0833563505,0,The Queen of the Damned (Vampire Chronicles (P...,Anne Rice,1999,Sagebrush Bound,http://images.amazon.com/images/P/0833563505.0...,http://images.amazon.com/images/P/0833563505.0...,http://images.amazon.com/images/P/0833563505.0...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [19]:
pt = finals_rating.pivot_table(index = "Book-Title", columns= 'User-ID', values= 'Book-Rating')

In [20]:
pt.fillna(0, inplace=True)

In [21]:
pt

User-ID,254,2276,2766,3363,4385,6251,6543,6575,7158,7346,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wuthering Heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
similarity_score = cosine_similarity(pt)

In [24]:
similarity_score

array([[1.        , 0.12637786, 0.01584756, ..., 0.1387288 , 0.08450515,
        0.0521102 ],
       [0.12637786, 1.        , 0.28824811, ..., 0.08010424, 0.18117097,
        0.1617243 ],
       [0.01584756, 0.28824811, 1.        , ..., 0.05165773, 0.05618509,
        0.12893887],
       ...,
       [0.1387288 , 0.08010424, 0.05165773, ..., 1.        , 0.07113412,
        0.02067643],
       [0.08450515, 0.18117097, 0.05618509, ..., 0.07113412, 1.        ,
        0.11219793],
       [0.0521102 , 0.1617243 , 0.12893887, ..., 0.02067643, 0.11219793,
        1.        ]])

In [25]:
sorted(list(enumerate(similarity_score[0])), key = lambda x:x[1], reverse=True)[1:6]

[(433, 0.31663755334122123),
 (514, 0.2819501153887623),
 (439, 0.2775401170783511),
 (67, 0.2731957063983398),
 (384, 0.2609981780284909)]

In [38]:
def recommend(book_name):
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])), key = lambda x:x[1], reverse=True)[1:20]
    
    data = []
    for i in similar_items:
        
        item = []
        temp_df = books[books["Book-Title"] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Title"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Author"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Image-URL-S"].values))
        
        data.append(item)
        
    return data

In [39]:
recommend('Zoya')

[['Fine Things',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0440200563.01.THUMBZZZ.jpg'],
 ['Secrets',
  'DANIELLE STEEL',
  'http://images.amazon.com/images/P/0440176484.01.THUMBZZZ.jpg'],
 ['Kaleidoscope',
  'June Stepansky',
  'http://images.amazon.com/images/P/0884092097.01.THUMBZZZ.jpg'],
 ['Five Days in Paris',
  'DANIELLE STEEL',
  'http://images.amazon.com/images/P/0440222842.01.THUMBZZZ.jpg'],
 ['Message from Nam',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0440209412.01.THUMBZZZ.jpg'],
 ['Heartbeat',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0385299087.01.THUMBZZZ.jpg'],
 ['Wanderlust',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0440193613.01.THUMBZZZ.jpg'],
 ['GARDEN OF SHADOWS (Dollanger Saga (Paperback))',
  'Ariel Jennifer Jones',
  'http://images.amazon.com/images/P/067164257X.01.THUMBZZZ.jpg'],
 ['Mirror Image',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0440224772.01.THUMBZZZ.jpg'],
 ['Before I Say Good-Bye',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671004573.01.THUMBZZZ.jpg'],
 ['Night Whispers',
  'Judith McNaught',
  'http://images.amazon.com/images/P/0671525743.01.THUMBZZZ.jpg'],
 ['The Long Road Home',
  'DANIELLE STEEL',
  'http://images.amazon.com/images/P/0385319568.01.THUMBZZZ.jpg'],
 ['Daddy',
  'DANIELLE STEEL',
  'http://images.amazon.com/images/P/0440207622.01.THUMBZZZ.jpg'],
 ['Vanished',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0385306032.01.THUMBZZZ.jpg'],
 ['Accident',
  'Danielle Steel',
  'http://images.amazon.com/images/P/0385306024.01.THUMBZZZ.jpg'],
 ['Lightning',
  'Dean R. Koontz',
  'http://images.amazon.com/images/P/0425115801.01.THUMBZZZ.jpg'],
 ['The Sands of Time',
  'Sidney Sheldon',
  'http://images.amazon.com/images/P/0446356832.01.THUMBZZZ.jpg'],
 ['That Camden Summer',
  'Lavyrle Spencer',
  'http://images.amazon.com/images/P/0399141200.01.THUMBZZZ.jpg'],
 ['The Cradle Will Fall',
  'Mary Higgins Clark',
  'http://images.amazon.com/images/P/0671741195.01.THUMBZZZ.jpg']]

In [28]:
best_df

,Book-Title,Book-Author,Image-URL-S,num_ratings,avg_ratings
0,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,6
4,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,6
7,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,6
11,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,6
13,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,5
...,...,...,...,...,...
716,The Prince of Tides,Pat Conroy,http://images.amazon.com/images/P/0553268880.0...,291,2
720,Whispers,BELVA PLAIN,http://images.amazon.com/images/P/0440216745.0...,286,2
730,Rising Sun,MICHAEL CRICHTON,http://images.amazon.com/images/P/0345380371.0...,278,2
733,Presumed Innocent,Scott Turow,http://images.amazon.com/images/P/0446359866.0...,294,2
739,Wild Animus,Rich Shapero,http://images.amazon.com/images/P/0971880107.0...,2502,1

In [36]:
import pickle
pickle.dump(best_df, open('best_df.pkl', 'wb'))

In [37]:
pickle.dump(pt, open('pt.pkl', 'wb'))
pickle.dump(similarity_score, open('similarity_score.pkl', 'wb'))
pickle.dump(books, open('books.pkl', 'wb'))